spring:
  application:
    name: Gateway_Service
  config:
    import: optional:configserver:${CONFIG_SERVICE:http://localhost:9999}

server:
  port: 8888

rsa:
  public-key: classpath:Keys/publicKey.pem
