apiVersion: apps/v1
kind: Deployment
metadata:
  name: chercheur-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chercheur-service
  template:
    metadata:
      labels:
        app: chercheur-service
    spec:
      containers:
        - name: chercheur-service
          image: g_lab-chercheur-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka
            - name: CONFIG_SERVICE
              value: http://config-service.default.svc.cluster.local:9999
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

---
---
apiVersion: v1
kind: Service
metadata:
  name: chercheur-service
spec:
  selector:
    app: chercheur-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer