apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-service
  template:
    metadata:
      labels:
        app: grafana-service
    spec:
      containers:
        - name: grafana-service
          image: grafana/grafana
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: LoadBalancer
  ports:
    - port: 6060
      targetPort: 3000
  selector:
    app: grafana-service