apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projet-service
  template:
    metadata:
      labels:
        app: projet-service
    spec:
      containers:
        - name: projet-service
          image: g_lab-projet-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka
            - name: CONFIG_SERVICE
              value: http://config-service.default.svc.cluster.local:9999
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
---
---
apiVersion: v1
kind: Service
metadata:
  name: projet-service
spec:
  selector:
    app: projet-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer